ckanext/ap_main/views/config.py
from __future__ import annotations

from typing import Union

from flask import Blueprint, Response

import ckan.plugins.toolkit as tk

from ckanext.ap_main.utils import ap_before_request

ap_config_list = Blueprint("ap_config_list", __name__, url_prefix="/admin-panel")
ap_config_list.before_request(ap_before_request)


@ap_config_list.route("/config")
def index() -> Union[str, Response]:
    return tk.render("admin_panel/config/config_list.html", extra_vars={})

ckanext/ap_main/templates/admin_panel/config/snippets/confirm_delete.html
{% extends 'admin_panel/base.html' %}

{% block ap_content %}
    <h1>Confirm delete</h1>
    <section class="module col-md-6 col-md-offset-3">
        <div class="module-content">
            {% block form %}
            <p>
            {{ _(messages.confirm[ent_type]) }}
            </p>
            <p class="form-actions">
                <form id="{{ ent_type }}-confirm-delete-form" action="{{ h.url_for('admin.trash') }}" method="POST">
                {{ h.csrf_input() }}
                <button class="btn btn-danger" type="submit" name="cancel">Cancel</button>
                <button class="btn btn-primary" type="submit" name="action" value="{{ ent_type }}">{{ _('Confirm Delete') }}</button>
                </form>
            </p>
            {% endblock %}
        </div>
    </section>
{% endblock ap_content %}

ckanext/ap_main/templates/admin_panel/config/snippets/editable_field.html
{#
name
option
data
errors
input_macro
#}
{% import 'macros/form.html' as form %}

{% set input_macro = input_macro or form.input %}

{% set id = name | replace(".", "-") %}

{% set field_id = "field-value-" ~ id %}
{% set customize_id = "field-customize-" ~ id %}

{% set attrs = {
    "class": "form-control",
    "data-module": "ap-toggle-state",
    "data-module-control": "#" ~ customize_id,
} %}

{% if not option.option %}
    {% do attrs.update(disabled="disabled") %}
{% endif %}


{% call input_macro(
    name,
    id=field_id,
    label=name,
    value=data[name] or option.value,
    error=errors[name],
    attrs=attrs,
    classes=["mb-1"]
) %}

{% endcall %}

{% if option.option %}
    {# option has custom value: enable remove checkbox to reset customization #}
    {{ form.checkbox(
        "reset:" ~ name,
        "field-reset-" ~ id,
        "Reset",
        value="1",
        checked=data["reset:" ~ name],
        classes=["mb-1"]
    ) }}
{% else %}
    {# option has no custom value: field is disabled unless customize checkbox
    is turned on to avoid meaningless updates #}
    {{ form.checkbox(
        null,
        customize_id,
        "Customize",
        value="1",
        checked=option.option,
        classes=["mb-1"]
    ) }}
{% endif %}

{{ h.render_markdown(h.editable_config_option_description(name), allow_html=true) }}

ckanext/ap_main/templates/admin_panel/config/snippets/home_breadcrumb.html
<li class="home">
    <a href="{{ h.url_for('ap_config_list.index') }}" aria-label="{{ _('Home') }}">
        <i class="fa fa-home"></i>
        <span>{{ _('Home') }}</span>
    </a>
</li>

{% if request.endpoint != "ap_config_list.index" %}
    <li><a href="{{ h.url_for('ap_config_list.index') }}">{{ _("Configurations list") }}</a></li>
{% endif %}